version: "3"
services:
  app:
    image: springwolf/springwolf-app:0.0.1
    links:
      - amqp
    volumes:
      - ./files:/app/docs
    ports:
      - "8999:8080"
    depends_on:
      - amqp

  amqp:
    image: rabbitmq:3.8-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'